version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"

  app1:
    build: .
    container_name: chat-app1
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis
      SERVER_PORT: 8080
    depends_on:
      - redis

  app2:
    build: .
    container_name: chat-app2
    ports:
      - "8081:8081"
    environment:
      SPRING_REDIS_HOST: redis
      SERVER_PORT: 8081
    depends_on:
      - redis
