spring:
  application:
    name: chat

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/chatdb
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: 6379

chat:
  redis:
    listener:
      enabled: true